# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('instrument_number', models.CharField(max_length=128)),
                ('memo', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_date', models.DateField()),
                ('postmark_date', models.DateField(blank=True, null=True)),
                ('processed_date', models.DateField(auto_now_add=True)),
                ('type_code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'ordering': ['account'],
                'verbose_name': 'Payment History',
                'db_table': 'cb_payments',
                'managed': False,
                'verbose_name_plural': 'Payment History',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['account'], 'verbose_name': 'Process Payment', 'verbose_name_plural': 'Process Payments'},
        ),
    ]
