# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_num', models.IntegerField()),
                ('amount', models.FloatField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('type_code', models.CharField(blank=True, max_length=64, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'ordering': ['invoice_date', 'account'],
                'db_table': 'cb_charges',
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
    ]
