# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_num', models.IntegerField()),
                ('amount', models.FloatField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('type_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['invoice_date', 'account'],
                'verbose_name': 'Charge History',
                'db_table': 'cb_charges',
                'managed': False,
                'verbose_name_plural': 'Charge History',
            },
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['invoice_date', 'account'], 'verbose_name': 'Add Charge', 'verbose_name_plural': 'Add Charges'},
        ),
    ]
