# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Custom User',
                'db_table': 'auth_user',
                'managed': False,
                'verbose_name_plural': 'Custom Users',
            },
        ),
    ]
