# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('accounts', '0002_account_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fence', 'Fence'), ('Pool', 'Pool')], max_length=64)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=64)),
                ('processed', models.DateField(auto_now_add=True, null=True)),
                ('requested', models.DateField()),
                ('waiver', models.BooleanField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'ordering': ['requested', 'account'],
                'db_table': 'cb_alterations',
                'verbose_name': 'Alteration',
                'verbose_name_plural': 'Alterations',
            },
        ),
    ]
