# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='finalized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='type',
            field=models.CharField(choices=[('Deck', 'Deck'), ('Driveway', 'Driveway'), ('Fence', 'Fence'), ('Garage', 'Garage'), ('Pool', 'Pool'), ('Room Addition', 'Room Addition'), ('Shed', 'Shed'), ('Other', 'Other')], max_length=64),
        ),
    ]
