# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0002_auto_20160128_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alteration',
            name='type',
        ),
        migrations.AddField(
            model_name='alteration',
            name='builder',
            field=models.CharField(blank=True, choices=[('contractor', 'Contractor'), ('homeowner', 'Home Owner')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='completion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='cost',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='deck',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='driveway',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='fence',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='file1',
            field=models.FileField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='file2',
            field=models.FileField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='file3',
            field=models.FileField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='garage',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='other',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='pool',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='roof',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='room',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='shed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteration',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='structureother',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
