# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0003_auto_20160824_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=64),
        ),
    ]
