# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0004_auto_20160825_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='buildername',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
