# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-31 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0005_alteration_buildername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alteration',
            name='buildername',
        ),
        migrations.AlterField(
            model_name='alteration',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
