# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cb_processes',
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
    ]
