# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateParameterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.DateField()),
            ],
            options={
                'verbose_name': 'Date Parameter',
                'db_table': 'cb_date_parameters',
                'managed': False,
                'verbose_name_plural': 'Date Parameter',
            },
        ),
        migrations.CreateModel(
            name='StringParameterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'String Parameter',
                'db_table': 'cb_string_parameters',
                'managed': False,
                'verbose_name_plural': 'String Parameter',
            },
        ),
        migrations.CreateModel(
            name='DateParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.DateField()),
            ],
            options={
                'db_table': 'cb_date_parameters',
                'verbose_name': 'Date Parameter',
                'verbose_name_plural': 'Date Parameter',
            },
        ),
        migrations.CreateModel(
            name='StringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cb_string_parameters',
                'verbose_name': 'String Parameter',
                'verbose_name_plural': 'String Parameter',
            },
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Admin Process', 'verbose_name_plural': 'Admin Processes'},
        ),
        migrations.AddField(
            model_name='stringparameter',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Process'),
        ),
        migrations.AddField(
            model_name='dateparameter',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Process'),
        ),
    ]
