# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20160209_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringparameter',
            name='parameter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
