# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20160209_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='run',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
