# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_process_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='code',
            field=models.CharField(default='x', max_length=16),
            preserve_default=False,
        ),
    ]
