# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_process_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateparameter',
            options={'verbose_name': 'Admin Date Parameter', 'verbose_name_plural': 'Admin Date Parameter'},
        ),
        migrations.AlterModelOptions(
            name='stringparameter',
            options={'verbose_name': 'Admin String Parameter', 'verbose_name_plural': 'Admin String Parameter'},
        ),
    ]
