# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20160209_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateparameter',
            name='parameter',
            field=models.DateField(blank=True, null=True),
        ),
    ]
