# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-active_flag', 'account_number'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
