# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160128_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deactivated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
