# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160503_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateField(auto_now_add=True, default='2009-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='default_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_default_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='account',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_property', to='properties.Property'),
        ),
    ]
