# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_default_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivateCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_flag', models.BooleanField()),
            ],
            options={
                'db_table': 'cb_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6)),
                ('suffix', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['prefix', 'suffix'],
                'verbose_name': 'Generate Account',
                'db_table': 'cb_gen_account_num_vw',
                'managed': False,
                'verbose_name_plural': 'Generate Accounts',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
