# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=8)),
                ('lot', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['section', 'lot'],
                'db_table': 'cb_properties',
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
