# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.DateField()),
            ],
            options={
                'db_table': 'cb_export_date_parameters',
                'verbose_name': 'Admin Date Parameter',
                'verbose_name_plural': 'Admin Date Parameter',
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=128)),
                ('run', models.BooleanField()),
            ],
            options={
                'db_table': 'cb_exports',
                'verbose_name': 'Admin Export',
                'verbose_name_plural': 'Admin Exports',
            },
        ),
        migrations.CreateModel(
            name='StringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('parameter', models.CharField(blank=True, max_length=128, null=True)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.Export')),
            ],
            options={
                'db_table': 'cb_export_string_parameter',
                'verbose_name': 'Admin String Parameter',
                'verbose_name_plural': 'Admin String Parameter',
            },
        ),
        migrations.AddField(
            model_name='dateparameter',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.Export'),
        ),
    ]
