# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateParameterUser',
            fields=[
                ('dateparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exports.DateParameter')),
            ],
            options={
                'verbose_name': 'Date Parameter',
                'db_table': 'cb_export_date_parameters',
                'managed': False,
                'verbose_name_plural': 'Date Parameter',
            },
            bases=('exports.dateparameter',),
        ),
        migrations.CreateModel(
            name='ExportUser',
            fields=[
                ('export_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exports.Export')),
            ],
            options={
                'verbose_name': 'Export',
                'db_table': 'cb_exports',
                'managed': False,
                'verbose_name_plural': 'Exports',
            },
            bases=('exports.export',),
        ),
        migrations.CreateModel(
            name='StringParameterUser',
            fields=[
                ('stringparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exports.StringParameter')),
            ],
            options={
                'verbose_name': 'String Parameter',
                'db_table': 'cb_export_string_parameters',
                'managed': False,
                'verbose_name_plural': 'String Parameter',
            },
            bases=('exports.stringparameter',),
        ),
    ]
