# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_auto_20160414_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='group',
            field=models.CharField(default='Treasurer', max_length=128),
            preserve_default=False,
        ),
    ]
