# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20160128_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_since',
            field=models.DateField(default='1950-01-01'),
            preserve_default=False,
        ),
    ]
