# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_owner_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
