# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['account'], 'verbose_name': 'Add Customer', 'verbose_name_plural': 'Add Customers'},
        ),
    ]
