# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=128)),
                ('balance', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['account_number'],
                'verbose_name': 'Customer',
                'db_table': 'cb_customers_vw',
                'managed': False,
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
