# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readonly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerview',
            table='cb_customer_summary_vw',
        ),
    ]
