# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='NEW', max_length=64),
            preserve_default=False,
        ),
    ]
