# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active_flag', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
